#!/bin/bash

print-usage() {
  echo "Usage: $(basename $0) {align|core|normalize|cov|test}"
}

case "$1" in
  --version)
    DIR=$(dirname $(which cmuts))
    VERSION=$(cat "$DIR/VERSION")
    echo "cmuts version $VERSION"
    exit 0
    ;;
  align)
    cmuts-align "${@:2}"
    ;;
  core)
    cmuts-core "${@:2}"
    ;;
  normalize)
    cmuts-normalize "${@:2}"
    ;;
  cov)
    cmuts-cov "${@:2}"
    ;;
  test)
    echo "Not implemented yet."
    exit 1
    ;;
  *)
    print-usage
    exit 1
    ;;
esac
