#!/bin/bash

set -eou pipefail

# Clean and create working directory

SCRIPT_DIR=$(pwd)
WORK_DIR=${SCRIPT_DIR}"/.tmp"
rm -rf ${WORK_DIR}
mkdir -p ${WORK_DIR}
pushd ${WORK_DIR} > /dev/null

NAME="onp"

FASTA="../data/$NAME/reference.fasta"
FILE="../data/$NAME/aln.bam"

CMUTS="cmuts.h5"
CMUTS_PROFILES="cmuts-profiles.h5"

RF_MUTS="rf_muts.txt"
RF_COV="rf_cov.txt"
RF_PROFILES="aln_norm/rool_118_RNA_reference.xml"

MIN_MAPQ=20
MIN_PHRED=20
MIN_LENGTH=2
COLLAPSE=2
WINDOW=1

cmuts \
    --fasta ${FASTA} \
    --output ${CMUTS} \
    --min-mapq ${MIN_MAPQ} \
    --min-phred ${MIN_PHRED} \
    --min-length ${MIN_LENGTH} \
    --collapse ${COLLAPSE} \
    --quality-window ${WINDOW} \
    --no-insertions \
    ${FILE}

echo

cmuts-normalize \
    $CMUTS \
    -o $CMUTS_PROFILES \
    --mod-ds ../data/$NAME/aln \
    --out-groups $NAME \
    --5p-primer-length 0 \
    --3p-primer-length 0

echo

rf-count \
    -f ${FASTA} \
    -m \
    --right-deletion \
    --no-discard-duplicates \
    --map-quality ${MIN_MAPQ} \
    --min-quality ${MIN_PHRED} \
    --discard-shorter ${MIN_LENGTH} \
    --collapse-consecutive \
    --max-collapse-distance ${COLLAPSE} \
    --no-insertions \
    --eval-surrounding \
    --median-quality 0 \
    --max-edit-distance 1.0 \
    ${FILE}

echo

rf-norm \
    --treated rf_count/aln.rc \
    -sm 4 \
    -nm 3

rf-rctools view rf_count/aln.rc | awk 'NR % 5 == 3' > $RF_MUTS
rf-rctools view rf_count/aln.rc | awk 'NR % 5 == 4' > $RF_COV

mkdir -p ../figures
python3 ../compare.py $CMUTS_PROFILES $RF_PROFILES $NAME

popd > /dev/null
