#!/bin/bash

set -euo pipefail
__time() {
    if [[ $(uname) == Darwin ]]; then
        gtime -f "%E %M KB" "$@"
    else
        /usr/bin/time -f "%E %M MB" "$@"
    fi
}

# Check if dependencies are installed
command -v samtools >/dev/null 2>&1 || { echo >&2 "Samtools is required but it's not installed. Exiting."; exit 1; }
command -v mpirun >/dev/null 2>&1 || { echo >&2 "MPI (mpirun) is required but it's not installed. Exiting."; exit 1; }

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CASES_DIR=${SCRIPT_DIR}"/.cases"
mkdir -p ${CASES_DIR}

LENGTH=100
REFERENCES=1024
QUALITY=0
WINDOW=0
MAX_INDEL=100
MIN_LENGTH=2
MAX_LENGTH=$((2 * LENGTH))
THREADS=8

EXP_H5="expected.h5"
CMUTS_H5="cmuts.h5"
RF_DIR="_rf_count"

echo ""
echo " ─────────────────────────────"
echo "   THREADS:          $THREADS"
echo "   REFERENCE LENGTH: $LENGTH"
echo "   REFERENCES:       $REFERENCES"
echo " ─────────────────────────────"

for QUERIES in 128 512 2048 8192 32768 131072; do

    echo "   QUERIES:          $QUERIES"
    echo " ─────────────────────────────"
    pushd ${CASES_DIR} > /dev/null

    SAM="aln_"${REFERENCES}"_"${QUERIES}".sam"
    BAM="aln_"${REFERENCES}"_"${QUERIES}".bam"
    FASTA="seq_"${REFERENCES}"_"${QUERIES}".fasta"

    if [ ! -f ${BAM} ]; then

        ../../../bin/cmuts-generate-tests \
            --length ${LENGTH} \
            --min-length ${MIN_LENGTH} \
            --queries ${QUERIES} \
            --references ${REFERENCES} \
            --out-fasta ${FASTA} \
            --out-sam ${SAM} \
            --out-h5 ${EXP_H5} \
            --min-quality ${QUALITY} \
            --max-indel-length ${MAX_INDEL} \
            --quality-window ${WINDOW}

        samtools calmd -b -@8 ${SAM} ${FASTA} > ${BAM}

        rm -rf ${SAM}
        rm -rf ${EXP_H5}

    fi

    echo -n "cmuts:    "
    __time mpirun -np ${THREADS} cmuts \
        -f ${FASTA} \
        -o ${CMUTS_H5} \
        --min-mapq ${QUALITY} \
        --quality-window ${WINDOW} \
        --min-length ${MIN_LENGTH} \
        --max-indel-length ${MAX_INDEL} \
        ${BAM} > /dev/null
    rm -rf ${CMUTS_H5}

    rm -rf ${RF_DIR}
    mkdir ${RF_DIR}
    cd ${RF_DIR}
    echo -n "rf-count: "
    __time rf-count \
        -wt ${THREADS} \
        -f ../${FASTA} \
        -m -orc \
        ../${BAM} > /dev/null 
    cd ..

    echo " ─────────────────────────────"

    popd > /dev/null

done

exit


QUERIES=256
echo ""
echo " ─────────────────────────────"
echo "   THREADS:          $THREADS"
echo "   REFERENCE LENGTH: $LENGTH"
echo "   QUERIES:          $QUERIES"
echo " ─────────────────────────────"

for REFERENCES in 128 512 2048 8192; do

    echo "   REFERENCES:       $REFERENCES"
    pushd ${CASES_DIR} > /dev/null

    SAM="aln_"${REFERENCES}"_"${QUERIES}".sam"
    BAM="aln_"${REFERENCES}"_"${QUERIES}".bam"
    FASTA="seq_"${REFERENCES}"_"${QUERIES}".fasta"

    if [ ! -f ${BAM} ]; then

        ../../_generate_tests \
            --length ${LENGTH} \
            --min-length ${MIN_LENGTH} \
            --queries ${QUERIES} \
            --references ${REFERENCES} \
            --out-fasta ${FASTA} \
            --out-sam ${SAM} \
            --out-h5 ${EXP_H5} \
            --min-quality ${QUALITY} \
            --quality-window ${WINDOW}

        samtools calmd -b -@8 ${SAM} ${FASTA} > ${BAM}

        rm -rf ${SAM}
        rm -rf ${EXP_H5}

    fi

    echo -n "cmuts:    "
    time mpirun -np ${THREADS} cmuts -f ${FASTA} -o ${CMUTS_H5} --min-mapq ${QUALITY} --quality-window ${WINDOW} --min-length ${MIN_LENGTH} ${BAM} > /dev/null
    rm -rf ${CMUTS_H5}

    rm -rf _rf
    mkdir _rf
    cd _rf
    echo -n "rf-count: "
    time rf-count -t ${THREADS} -f ../${FASTA} ../${BAM}
    cd ..
    rm -rf _rf

    echo " ─────────────────────────────"

    popd > /dev/null

done
