#!/bin/bash

set -euo pipefail

# Check if dependencies are installed
command -v samtools >/dev/null 2>&1 || { echo >&2 "Samtools is required but it's not installed. Exiting."; exit 1; }
command -v mpirun >/dev/null 2>&1 || { echo >&2 "MPI (mpirun) is required but it's not installed. Exiting."; exit 1; }

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CASES_DIR=${SCRIPT_DIR}"/.cases"
mkdir -p ${CASES_DIR}

LENGTH=100
REFERENCES=1024
QUALITY=0
WINDOW=0
MIN_LENGTH=2
MAX_LENGTH=$((2 * LENGTH))
THREADS=1

EXP_H5="expected.h5"
CMUTS_H5="cmuts.h5"

echo ""
echo " ─────────────────────────────"
echo "   THREADS:          $THREADS"
echo "   REFERENCE LENGTH: $LENGTH"
echo "   REFERENCES:       $REFERENCES"
echo " ─────────────────────────────"

for QUERIES in 128 512 2048 8192 32768 131072; do

    echo "   QUERIES:          $QUERIES"
    pushd ${CASES_DIR} > /dev/null

    SAM="aln_"${REFERENCES}"_"${QUERIES}".sam"
    BAM="aln_"${REFERENCES}"_"${QUERIES}".bam"
    FASTA="seq_"${REFERENCES}"_"${QUERIES}".fasta"

    if [ ! -f ${BAM} ]; then

        ../../../bin/cmuts-generate-tests \
            --length ${LENGTH} \
            --min-length ${MIN_LENGTH} \
            --queries ${QUERIES} \
            --references ${REFERENCES} \
            --out-fasta ${FASTA} \
            --out-sam ${SAM} \
            --out-h5 ${EXP_H5} \
            --min-quality ${QUALITY} \
            --quality-window ${WINDOW}

        samtools calmd -b -@8 ${SAM} ${FASTA} > ${BAM}

        rm -rf ${SAM}
        rm -rf ${EXP_H5}

    fi

    /usr/bin/time mpirun -np ${THREADS} cmuts -f ${FASTA} -o ${CMUTS_H5} --min-mapq ${QUALITY} --quality-window ${WINDOW} --min-length ${MIN_LENGTH} ${BAM} > /dev/null
    rm -rf ${CMUTS_H5}
    echo " ─────────────────────────────"

    popd > /dev/null

done

exit


QUERIES=256
echo ""
echo " ─────────────────────────────"
echo "   THREADS:          $THREADS"
echo "   REFERENCE LENGTH: $LENGTH"
echo "   QUERIES:          $QUERIES"
echo " ─────────────────────────────"

for REFERENCES in 128 512 2048 8192; do

    echo "   REFERENCES:       $REFERENCES"
    pushd ${CASES_DIR} > /dev/null

    SAM="aln_"${REFERENCES}"_"${QUERIES}".sam"
    BAM="aln_"${REFERENCES}"_"${QUERIES}".bam"
    FASTA="seq_"${REFERENCES}"_"${QUERIES}".fasta"

    if [ ! -f ${BAM} ]; then

        ../../_generate_tests \
            --length ${LENGTH} \
            --min-length ${MIN_LENGTH} \
            --queries ${QUERIES} \
            --references ${REFERENCES} \
            --out-fasta ${FASTA} \
            --out-sam ${SAM} \
            --out-h5 ${EXP_H5} \
            --min-quality ${QUALITY} \
            --quality-window ${WINDOW}

        samtools calmd -b -@8 ${SAM} ${FASTA} > ${BAM}

        rm -rf ${SAM}
        rm -rf ${EXP_H5}

    fi

    /usr/bin/time mpirun -np ${THREADS} cmuts -f ${FASTA} -o ${CMUTS_H5} --min-mapq ${QUALITY} --quality-window ${WINDOW} --min-length ${MIN_LENGTH} ${BAM} > /dev/null
    rm -rf ${CMUTS_H5}
    echo " ─────────────────────────────"

    popd > /dev/null

done
