#!/usr/bin/env python3

import argparse
import h5py
import numpy as np
import cmuts
from typing import Union


def _seq_from_fasta(file: str, n: int = 0) -> str:

    seq = ""
    count = 0

    with open(file, 'r') as f:
        for line in f:
            if line.startswith(">"):
                count += 1
                continue
            if count == n + 1:
                seq += line.strip()

    return seq.upper().replace("U", "T")


parser = argparse.ArgumentParser(
    description="Color structure by reactivity data from HDF5 file"
)
parser.add_argument(
    "--file",
    help="Path to HDF5 file",
    required=True,
)
parser.add_argument(
    "--dataset",
    help="Dataset name in HDF5 file",
    required=True,
)
parser.add_argument(
    "--cif",
    help="Path to .cif structure file",
)
parser.add_argument(
    "--fasta",
    help="Path to .fasta file of the sequence which was chemically probed.",
    required=True,
)
parser.add_argument(
    "--bin",
    default="ChimeraX",
    help="Path to ChimeraX binary.",
)
parser.add_argument(
    "--index",
    type=int,
    default=0,
    help="Index of reactivity in the dataset.",
)
parser.add_argument(
    "--chain",
    nargs='?',
    default=None,
    help="Chain of the structure to color. All if none is specified.",
)
parser.add_argument(
    "--color",
    default="indianred",
    help="The ChimeraX color to use for highly reactive bases.",
)
parser.add_argument(
    "--trim-5p",
    type=int,
    default=0,
    help="Trim this many bases from the 5' end of the reactivity data.",
)
parser.add_argument(
    "--trim-3p",
    type=int,
    default=0,
    help="Trim this many bases from the 3' end of the reactivity data.",
)


def _load_reactivity(
    file: str,
    dataset: str,
    index: int,
    trim5: int = 0,
    trim3: int = 0,
) -> np.ndarray:

    with h5py.File(file, 'r') as f:
        data = f[dataset]
        if data.ndim == 2:
            data = data[index]
        else:
            data = data[:]

    if trim5:
        data = data[trim5:]
    if trim3:
        data = data[:-trim3]

    return data


def _overlay_on_cif(
    file: str,
    dataset: str,
    index: int,
    fasta: str,
    cif: str,
    trim5: int,
    trim3: int,
    color: str,
    chain: str,
    bin: str,
) -> None:

    reactivity = _load_reactivity(file, dataset, index, trim5, trim3)
    seq = _seq_from_fasta(fasta, index)
    cmuts.visualize.cif(reactivity, seq, cif, color, chain, bin)

if __name__ == "__main__":

    args = parser.parse_args()
    _overlay_on_cif(
        args.file,
        args.dataset,
        args.index,
        args.fasta,
        args.cif,
        args.trim_5p,
        args.trim_3p,
        args.color,
        args.chain,
        args.bin,
    )
