"""
cmuts: Chemical mutation profiling for RNA structure analysis.

This package provides tools for computing reactivity profiles from mutation
count data generated by chemical probing experiments (e.g., MaP-seq, SHAPE-MaP).

Key Classes:
    ProbingData: Container for reactivity profiles, errors, and quality metrics.
    Opts: Configuration options for reactivity computation.
    DataGroups: Specifies HDF5 group paths for modified/unmodified conditions.

Key Functions:
    compute_reactivity: Transform mutation counts to normalized reactivity.
    stats: Print summary statistics for probing data.
    title: Format version banner for CLI output.

Submodules:
    visualize: Plotting and visualization tools.
    normalize: CLI for batch normalization.

Example:
    >>> import cmuts
    >>> import h5py
    >>> with h5py.File("counts.h5", "r") as f:
    ...     mod, nomod, combined = cmuts.compute_reactivity(f, "ref.fasta", opts)
    >>> print(combined)  # Displays summary statistics
"""

from importlib.metadata import version as _get_version

# Visualization submodule
from . import visualize

# Core data types and functions
from .internal import (
    DataGroups,
    Experiment,
    ExperimentResult,
    Opts,
    ProbingData,
    SNRCurves,
    compute_reactivities,
    compute_reactivity,
    compute_snr_curves,
    save_groups,
)
from .normalize import Scheme, normalization, register, requires_sequence, scheme_names

# Output formatting
from .output import (
    stats,
    subtitle,
    title,
)

__version__ = _get_version("cmuts")

__all__ = [
    "__version__",
    "DataGroups",
    "Experiment",
    "ExperimentResult",
    "Opts",
    "ProbingData",
    "SNRCurves",
    "Scheme",
    "compute_reactivities",
    "compute_reactivity",
    "compute_snr_curves",
    "normalization",
    "register",
    "requires_sequence",
    "save_groups",
    "scheme_names",
    "stats",
    "subtitle",
    "title",
    "visualize",
]
