#!/usr/bin/env python3
"""Generate bash and zsh completion scripts for cmuts from argument JSON configs."""

import json
import sys
from pathlib import Path


def load_args(json_path: str) -> list[dict]:
    with open(json_path) as f:
        config = json.load(f)
    args = []
    for group in config["groups"]:
        for arg in group["args"]:
            if arg["long"].startswith("--"):
                entry = {"long": arg["long"], "help": arg["help"]}
                if arg.get("short"):
                    entry["short"] = arg["short"]
                if arg["type"] != "bool":
                    entry["takes_value"] = True
                args.append(entry)
    return args


def generate_bash(core_args: list[dict], generate_args: list[dict], out: str):
    core_opts = " ".join(a["long"] for a in core_args)
    core_shorts = " ".join(a["short"] for a in core_args if a.get("short"))
    gen_opts = " ".join(a["long"] for a in generate_args)
    gen_shorts = " ".join(a["short"] for a in generate_args if a.get("short"))

    script = f'''\
# bash completion for cmuts
# Generated by scripts/generate_completions.py — do not edit manually

_cmuts() {{
    local cur prev words cword
    _init_completion || return

    local subcommands="align core generate normalize plot visualize test"

    # Find subcommand
    local subcmd=""
    local i
    for ((i=1; i < cword; i++)); do
        case "${{words[i]}}" in
            align|core|generate|normalize|plot|visualize|test)
                subcmd="${{words[i]}}"
                break
                ;;
        esac
    done

    if [[ -z "$subcmd" ]]; then
        case "$cur" in
            -*)
                COMPREPLY=($(compgen -W "--help --version --log" -- "$cur"))
                ;;
            *)
                COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))
                ;;
        esac
        return
    fi

    case "$subcmd" in
        core)
            case "$prev" in
                -o|--output)
                    _filedir h5
                    return
                    ;;
                -f|--fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "{core_shorts} {core_opts} --threads --help" -- "$cur"))
                    ;;
                *)
                    _filedir '@(sam|bam|cram)'
                    ;;
            esac
            ;;
        align)
            case "$prev" in
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                --output)
                    _filedir -d
                    return
                    ;;
                --barcodes)
                    _filedir '@(csv|tsv|txt)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--fasta --output --overwrite --rebuild --verbose --threads --barcodes --trim-5 --trim-3 --local --pairs --help --version" -- "$cur"))
                    ;;
                *)
                    _filedir '@(fastq|fastq.gz|fq|fq.gz|bam)'
                    ;;
            esac
            ;;
        generate)
            case "$prev" in
                --out-fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                -o|--out)
                    _filedir '@(sam|bam|cram)'
                    return
                    ;;
                --out-h5)
                    _filedir h5
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "{gen_shorts} {gen_opts} --help" -- "$cur"))
                    ;;
            esac
            ;;
        normalize)
            case "$prev" in
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                -o|--out)
                    _filedir h5
                    return
                    ;;
                --norm)
                    COMPREPLY=($(compgen -W "ubr raw outlier" -- "$cur"))
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--mod --nomod --fasta --group -o --out --overwrite --clip-low --clip-high --blank-5p --blank-3p --blank-cutoff --norm-independent --norm --norm-cutoff --norm-percentile --no-insertions --no-deletions --sig --help" -- "$cur"))
                    ;;
                *)
                    _filedir h5
                    ;;
            esac
            ;;
        plot)
            case "$prev" in
                --files)
                    _filedir h5
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--files --datasets --labels --index --trim-5p --trim-3p --help" -- "$cur"))
                    ;;
            esac
            ;;
        visualize)
            case "$prev" in
                --file)
                    _filedir h5
                    return
                    ;;
                --cif)
                    _filedir '@(cif|mmcif)'
                    return
                    ;;
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--file --dataset --cif --fasta --bin --index --chain --color --trim-5p --trim-3p --help" -- "$cur"))
                    ;;
            esac
            ;;
        test)
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--quick --cram" -- "$cur"))
                    ;;
            esac
            ;;
    esac
}}

complete -F _cmuts cmuts
'''

    Path(out).write_text(script)


def generate_zsh(core_args: list[dict], generate_args: list[dict], out: str):
    def zsh_opts(args: list[dict], indent: int = 24) -> list[str]:
        pad = " " * indent
        lines = []
        for a in args:
            desc = a["help"].replace("'", "'\\''").replace("[", "\\[").replace("]", "\\]")
            takes = ": :" if a.get("takes_value") else ""
            if a.get("short"):
                lines.append(f"{pad}'({a['short']} {a['long']}){a['short']}[{desc}]{takes}'")
                lines.append(f"{pad}'({a['short']} {a['long']}){a['long']}[{desc}]{takes}'")
            else:
                lines.append(f"{pad}'{a['long']}[{desc}]{takes}'")
        return lines

    core_lines = zsh_opts(core_args)
    core_lines.append("                        '--threads[Number of MPI processes]: :'")
    core_lines.append("                        '*:input files:_files -g \"*.{sam,bam,cram}\"'")

    gen_lines = zsh_opts(generate_args)

    def join_args(lines: list[str]) -> str:
        return " \\\n".join(lines)

    script = """\
#compdef cmuts
# Generated by scripts/generate_completions.py — do not edit manually

_cmuts() {
    local -a subcommands
    subcommands=(
        'align:Align FASTQ files to a reference'
        'core:Count chemical mutations from aligned reads'
        'generate:Generate synthetic test data'
        'normalize:Normalize mutation counts to reactivity profiles'
        'plot:Plot reactivity profiles'
        'visualize:Color 3D structures by reactivity'
        'test:Run integration tests'
    )

    _arguments -C \\
        '(-h --help)'{-h,--help}'[Show help]' \\
        '(-v --version)'{-v,--version}'[Show version]' \\
        '--log[Log file]: :_files' \\
        '1:subcommand:->subcmd' \\
        '*::arg:->args'

    case "$state" in
        subcmd)
            _describe 'subcommand' subcommands
            ;;
        args)
            case "$words[1]" in
                core)
                    _arguments \\
""" + join_args(core_lines) + """
                    ;;
                align)
                    _arguments \\
                        '--fasta[Reference FASTA file]: :_files -g "*.{fa,fasta,fna}"' \\
                        '--output[Output directory]: :_files -/' \\
                        '--overwrite[Overwrite existing output]' \\
                        '--rebuild[Rebuild index files]' \\
                        '--verbose[Enable verbose output]' \\
                        '--threads[Number of threads]: :' \\
                        '--barcodes[Barcode file for demultiplexing]: :_files' \\
                        "--trim-5[5' adapter sequence]: :" \\
                        "--trim-3[3' adapter sequence]: :" \\
                        '--local[Use local alignment mode]' \\
                        '--pairs[Paired-end read files]: :_files -g "*.{fastq,fastq.gz,fq,fq.gz}"' \\
                        '*:input files:_files -g "*.{fastq,fastq.gz,fq,fq.gz,bam}"'
                    ;;
                generate)
                    _arguments \\
""" + join_args(gen_lines) + """
                    ;;
                normalize)
                    _arguments \\
                        '--mod[Modified sample dataset names]: :' \\
                        '--nomod[Non-modified sample dataset names]: :' \\
                        '--fasta[Reference FASTA file]: :_files -g "*.{fa,fasta,fna}"' \\
                        '--group[Output group name]: :' \\
                        '(-o --out)'{-o,--out}'[Output HDF5 file]: :_files -g "*.h5"' \\
                        '--overwrite[Overwrite existing file]' \\
                        '--clip-low[Clip negative reactivity values]' \\
                        '--clip-high[Clip reactivity values above 1]' \\
                        "--blank-5p[NaN out bases on 5' end]: :" \\
                        "--blank-3p[NaN out bases on 3' end]: :" \\
                        '--blank-cutoff[Min reads for position]: :' \\
                        '--norm-independent[Normalize each profile separately]' \\
                        '--norm[Normalization method]: :(ubr raw outlier)' \\
                        '--norm-cutoff[Min reads for normalization]: :' \\
                        '--norm-percentile[Normalization percentile]: :' \\
                        '--no-insertions[Exclude insertions from reactivity]' \\
                        '--no-deletions[Exclude deletions from reactivity]' \\
                        '--sig[Significance level]: :' \\
                        '*:input file:_files -g "*.h5"'
                    ;;
                plot)
                    _arguments \\
                        '--files[HDF5 input files]: :_files -g "*.h5"' \\
                        '--datasets[Dataset names]: :' \\
                        '--labels[Plot labels]: :' \\
                        '--index[Dataset index]: :' \\
                        "--trim-5p[Trim bases from 5' end]: :" \\
                        "--trim-3p[Trim bases from 3' end]: :"
                    ;;
                visualize)
                    _arguments \\
                        '--file[HDF5 input file]: :_files -g "*.h5"' \\
                        '--dataset[Dataset name]: :' \\
                        '--cif[CIF structure file]: :_files -g "*.{cif,mmcif}"' \\
                        '--fasta[Reference FASTA file]: :_files -g "*.{fa,fasta,fna}"' \\
                        '--bin[ChimeraX binary path]: :_files' \\
                        '--index[Dataset index]: :' \\
                        '--chain[Structure chain]: :' \\
                        '--color[ChimeraX color name]: :' \\
                        "--trim-5p[Trim bases from 5' end]: :" \\
                        "--trim-3p[Trim bases from 3' end]: :"
                    ;;
                test)
                    _arguments \\
                        '--quick[Run quick tests only]' \\
                        '--cram[Run CRAM-specific tests only]'
                    ;;
            esac
            ;;
    esac
}

_cmuts "$@"
"""

    Path(out).write_text(script)


if __name__ == "__main__":
    script_dir = Path(__file__).parent.parent
    config_dir = script_dir / "config"
    completions_dir = script_dir / "completions"
    completions_dir.mkdir(exist_ok=True)

    core_args = load_args(config_dir / "cmuts_args.json")
    gen_args = load_args(config_dir / "tests_args.json")

    generate_bash(core_args, gen_args, completions_dir / "cmuts.bash")
    generate_zsh(core_args, gen_args, completions_dir / "_cmuts")

    print(f"Generated {completions_dir / 'cmuts.bash'}")
    print(f"Generated {completions_dir / '_cmuts'}")
