# AUTOMATICALLY GENERATED by `shtab`

_shtab_cmuts_subparsers=('core' 'generate' 'normalize' 'plot' 'visualize' 'align' 'test')

_shtab_cmuts_option_strings=('-h' '--help' '-v' '--version' '--log')
_shtab_cmuts_core_option_strings=('-h' '--help' '-o' '--output' '-f' '--fasta' '--overwrite' '--rebuild' '-c' '--compression' '--print-every' '-v' '--verbose' '--pairwise' '--tokenize' '--token-map' '--min-mapq' '--min-phred' '--min-length' '--max-length' '--max-hamming' '--secondary' '--downsample' '--ignore-bases' '--max-indel-length' '--quality-window' '--collapse' '--chunk-size' '--no-mismatches' '--no-insertions' '--no-deletions' '--no-reverse' '--only-reverse' '--uniform-spread' '--no-spread' '--disable-ambiguous' '--no-match-filter' '--no-insertion-filter' '--no-deletion-filter' '--threads')
_shtab_cmuts_generate_option_strings=('-h' '--help' '--length' '--queries' '--references' '--seed' '--out-fasta' '-o' '--out' '--out-h5' '--min-mapq' '--min-phred' '--min-length' '--max-length' '--max-indel-length' '--collapse' '--quality-window' '--no-mismatches' '--no-insertions' '--no-deletions')
_shtab_cmuts_normalize_option_strings=('-h' '--help' '--mod' '--nomod' '--group' '--groups' '--independent-norm' '--fasta' '-o' '--out' '--overwrite' '--clip-below' '--clip-above' '--blank-5p' '--blank-3p' '--blank-cutoff' '--norm' '--no-insertions' '--no-deletions' '--sig')
_shtab_cmuts_plot_option_strings=('-h' '--help' '--files' '--datasets' '--labels' '--index' '--trim-5p' '--trim-3p')
_shtab_cmuts_visualize_option_strings=('-h' '--help' '--file' '--dataset' '--cif' '--fasta' '--bin' '--index' '--chain' '--color' '--trim-5p' '--trim-3p' '--vmin' '--vmax' '--defattr-out' '--no-chimerax')
_shtab_cmuts_align_option_strings=('-h' '--help' '--fasta' '--output' '--overwrite' '--rebuild' '--verbose' '--threads' '--barcodes' '--trim-5' '--trim-3' '--local' '--pairs')
_shtab_cmuts_test_option_strings=('-h' '--help' '--quick' '--cram')

_shtab_cmuts___log_COMPGEN=_shtab_compgen_files
_shtab_cmuts_core_pos_0_COMPGEN=_shtab_compgen_files
_shtab_cmuts_core__o_COMPGEN=_shtab_compgen_files
_shtab_cmuts_core___output_COMPGEN=_shtab_compgen_files
_shtab_cmuts_core__f_COMPGEN=_shtab_compgen_files
_shtab_cmuts_core___fasta_COMPGEN=_shtab_compgen_files
_shtab_cmuts_generate___out_fasta_COMPGEN=_shtab_compgen_files
_shtab_cmuts_generate__o_COMPGEN=_shtab_compgen_files
_shtab_cmuts_generate___out_COMPGEN=_shtab_compgen_files
_shtab_cmuts_generate___out_h5_COMPGEN=_shtab_compgen_files
_shtab_cmuts_normalize_pos_0_COMPGEN=_shtab_compgen_files
_shtab_cmuts_normalize___fasta_COMPGEN=_shtab_compgen_files
_shtab_cmuts_normalize__o_COMPGEN=_shtab_compgen_files
_shtab_cmuts_normalize___out_COMPGEN=_shtab_compgen_files
_shtab_cmuts_plot___files_COMPGEN=_shtab_compgen_files
_shtab_cmuts_visualize___file_COMPGEN=_shtab_compgen_files
_shtab_cmuts_visualize___cif_COMPGEN=_shtab_compgen_files
_shtab_cmuts_visualize___fasta_COMPGEN=_shtab_compgen_files
_shtab_cmuts_align_pos_0_COMPGEN=_shtab_compgen_files
_shtab_cmuts_align___fasta_COMPGEN=_shtab_compgen_files
_shtab_cmuts_align___output_COMPGEN=_shtab_compgen_files
_shtab_cmuts_align___barcodes_COMPGEN=_shtab_compgen_files
_shtab_cmuts_align___pairs_COMPGEN=_shtab_compgen_files

_shtab_cmuts_pos_0_choices=('core' 'generate' 'normalize' 'plot' 'visualize' 'align' 'test')
_shtab_cmuts_normalize___norm_choices=('raw' 'ubr' 'outlier')

_shtab_cmuts_pos_0_nargs=A...
_shtab_cmuts__h_nargs=0
_shtab_cmuts___help_nargs=0
_shtab_cmuts__v_nargs=0
_shtab_cmuts___version_nargs=0
_shtab_cmuts_core_pos_0_nargs=*
_shtab_cmuts_core__h_nargs=0
_shtab_cmuts_core___help_nargs=0
_shtab_cmuts_core___overwrite_nargs=0
_shtab_cmuts_core___rebuild_nargs=0
_shtab_cmuts_core__v_nargs=0
_shtab_cmuts_core___verbose_nargs=0
_shtab_cmuts_core___pairwise_nargs=0
_shtab_cmuts_core___tokenize_nargs=0
_shtab_cmuts_core___secondary_nargs=0
_shtab_cmuts_core___no_mismatches_nargs=0
_shtab_cmuts_core___no_insertions_nargs=0
_shtab_cmuts_core___no_deletions_nargs=0
_shtab_cmuts_core___no_reverse_nargs=0
_shtab_cmuts_core___only_reverse_nargs=0
_shtab_cmuts_core___uniform_spread_nargs=0
_shtab_cmuts_core___no_spread_nargs=0
_shtab_cmuts_core___disable_ambiguous_nargs=0
_shtab_cmuts_core___no_match_filter_nargs=0
_shtab_cmuts_core___no_insertion_filter_nargs=0
_shtab_cmuts_core___no_deletion_filter_nargs=0
_shtab_cmuts_generate__h_nargs=0
_shtab_cmuts_generate___help_nargs=0
_shtab_cmuts_generate___no_mismatches_nargs=0
_shtab_cmuts_generate___no_insertions_nargs=0
_shtab_cmuts_generate___no_deletions_nargs=0
_shtab_cmuts_normalize__h_nargs=0
_shtab_cmuts_normalize___help_nargs=0
_shtab_cmuts_normalize___mod_nargs=+
_shtab_cmuts_normalize___nomod_nargs=+
_shtab_cmuts_normalize___independent_norm_nargs=0
_shtab_cmuts_normalize___overwrite_nargs=0
_shtab_cmuts_normalize___no_insertions_nargs=0
_shtab_cmuts_normalize___no_deletions_nargs=0
_shtab_cmuts_plot__h_nargs=0
_shtab_cmuts_plot___help_nargs=0
_shtab_cmuts_plot___files_nargs=+
_shtab_cmuts_plot___datasets_nargs=+
_shtab_cmuts_plot___labels_nargs=+
_shtab_cmuts_visualize__h_nargs=0
_shtab_cmuts_visualize___help_nargs=0
_shtab_cmuts_visualize___chain_nargs=?
_shtab_cmuts_visualize___no_chimerax_nargs=0
_shtab_cmuts_align_pos_0_nargs=*
_shtab_cmuts_align__h_nargs=0
_shtab_cmuts_align___help_nargs=0
_shtab_cmuts_align___overwrite_nargs=0
_shtab_cmuts_align___rebuild_nargs=0
_shtab_cmuts_align___verbose_nargs=0
_shtab_cmuts_align___local_nargs=0
_shtab_cmuts_test__h_nargs=0
_shtab_cmuts_test___help_nargs=0
_shtab_cmuts_test___quick_nargs=0
_shtab_cmuts_test___cram_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_cmuts() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_cmuts
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  elif [[ "${previous_word}" == ">" || "${previous_word}" == ">>" ||
          "${previous_word}" =~ ^[12]">" || "${previous_word}" =~ ^[12]">>" ]]; then
    # handle redirection operators
    COMPREPLY=( $(compgen -f -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_cmuts cmuts