# bash completion for cmuts
# Generated by scripts/generate_completions.py — do not edit manually

_cmuts() {
    local cur prev words cword
    _init_completion || return

    local subcommands="align core generate normalize plot visualize test"

    # Find subcommand
    local subcmd=""
    local i
    for ((i=1; i < cword; i++)); do
        case "${words[i]}" in
            align|core|generate|normalize|plot|visualize|test)
                subcmd="${words[i]}"
                break
                ;;
        esac
    done

    if [[ -z "$subcmd" ]]; then
        case "$cur" in
            -*)
                COMPREPLY=($(compgen -W "--help --version --log" -- "$cur"))
                ;;
            *)
                COMPREPLY=($(compgen -W "$subcommands" -- "$cur"))
                ;;
        esac
        return
    fi

    case "$subcmd" in
        core)
            case "$prev" in
                -o|--output)
                    _filedir h5
                    return
                    ;;
                -f|--fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "-o -f -c -v --output --fasta --overwrite --rebuild --compression --print-every --verbose --pairwise --tokenize --min-mapq --min-phred --min-length --max-length --max-hamming --secondary --downsample --ignore-bases --max-indel-length --quality-window --collapse --chunk-size --no-mismatches --no-insertions --no-deletions --no-reverse --only-reverse --uniform-spread --no-spread --disable-ambiguous --no-match-filter --no-insertion-filter --no-deletion-filter --threads --help" -- "$cur"))
                    ;;
                *)
                    _filedir '@(sam|bam|cram)'
                    ;;
            esac
            ;;
        align)
            case "$prev" in
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                --output)
                    _filedir -d
                    return
                    ;;
                --barcodes)
                    _filedir '@(csv|tsv|txt)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--fasta --output --overwrite --rebuild --verbose --threads --barcodes --trim-5 --trim-3 --local --pairs --help --version" -- "$cur"))
                    ;;
                *)
                    _filedir '@(fastq|fastq.gz|fq|fq.gz|bam)'
                    ;;
            esac
            ;;
        generate)
            case "$prev" in
                --out-fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                -o|--out)
                    _filedir '@(sam|bam|cram)'
                    return
                    ;;
                --out-h5)
                    _filedir h5
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "-o --length --queries --references --seed --out-fasta --out --out-h5 --min-mapq --min-phred --min-length --max-length --max-indel-length --collapse --quality-window --no-mismatches --no-insertions --no-deletions --help" -- "$cur"))
                    ;;
            esac
            ;;
        normalize)
            case "$prev" in
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
                -o|--out)
                    _filedir h5
                    return
                    ;;
                --norm)
                    COMPREPLY=($(compgen -W "ubr raw outlier" -- "$cur"))
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--mod --nomod --fasta --group -o --out --overwrite --clip-low --clip-high --blank-5p --blank-3p --blank-cutoff --norm-independent --norm --norm-cutoff --norm-percentile --no-insertions --no-deletions --sig --help" -- "$cur"))
                    ;;
                *)
                    _filedir h5
                    ;;
            esac
            ;;
        plot)
            case "$prev" in
                --files)
                    _filedir h5
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--files --datasets --labels --index --trim-5p --trim-3p --help" -- "$cur"))
                    ;;
            esac
            ;;
        visualize)
            case "$prev" in
                --file)
                    _filedir h5
                    return
                    ;;
                --cif)
                    _filedir '@(cif|mmcif)'
                    return
                    ;;
                --fasta)
                    _filedir '@(fa|fasta|fna)'
                    return
                    ;;
            esac
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--file --dataset --cif --fasta --bin --index --chain --color --trim-5p --trim-3p --help" -- "$cur"))
                    ;;
            esac
            ;;
        test)
            case "$cur" in
                -*)
                    COMPREPLY=($(compgen -W "--quick --cram" -- "$cur"))
                    ;;
            esac
            ;;
    esac
}

complete -F _cmuts cmuts
